### ISSUE TITLE
github-publish/check returning a 500 internal server errror, but works fine in local development build

### ISSUE THREAD

**Issue by Callum21** [phantomstudios/strapi-plugin-github-publish#28]
Hello, 

On our production app, the Github Publishing check status is stuck and returns an error 500 in the console. When the app is run locally in the development build, the check works fine. 

Strapi Version: 3.5.4
Plugin Version: 0.1.0 

Has anyone else ran into this issue?

**Comment by bmbaron** [comment]
Hi @Callum21, maybe you've solved this already but I was having the same issue, and it ended up being that I didn't include 

**workflow_dispatch:**

under my "on" condition in the yaml file that I was trying to trigger. Adding that allows the file to be run manually or by a trigger such as the plugin. 

  
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch


Also, there's a fork of this repo which I'm using which is here: https://market.strapi.io/plugins/strapi-plugin-site-publisher

**Comment by Callum21** [comment]
Hello, I have still not solved this. 

in my yaml file I have: 

on:
  workflow_dispatch:
  push:
    branches:
      - master

The site I am using the plugin on is using an older version of Strapi so I am unable to use the new plugin for Strapi v4. 

Thanks
